### ISSUE TITLE
module broke recently

### ISSUE THREAD

**Issue by joostgrunwald** [KoichiYasuoka/spaCy-Alpino#1]
It worked fine for me until it suddenly stopped working, now doesn't work anymore on two different computers, a server and google collab, convinced the error lies within this package or its dependencies.  (testen with python 3.7, 3.8 and the collab version)

ValueError                                Traceback (most recent call last)
[<ipython-input-1-716cc897b35b>](https://localhost:8080/#) in <module>
      5 import spacy_alpino
      6 nlp=spacy_alpino.load("Alpino/bin/Alpino")
----> 7 doc=nlp("Zorg dat daar geen zwarte hond tussen komt.")
      8 import deplacy
      9 deplacy.render(doc)

3 frames
[/usr/local/lib/python3.7/dist-packages/spacy_alpino/alpino.py](https://localhost:8080/#) in __call__(self, doc)
     37       with urllib.request.urlopen(ALPINO_URL+"alpino?words="+urllib.parse.quote(t)) as r:
     38         q=r.read().decode("utf-8")
---> 39       i=q.index("conllu?tmp/")
     40       with urllib.request.urlopen(ALPINO_URL+q[i:q.index("'",i)]) as r:
     41         u=r.read().decode("utf-8")

**Comment by joostgrunwald** [comment]
@KoichiYasuoka

**Comment by KoichiYasuoka** [comment]
```
     37     with urllib.request.urlopen(ALPINO_URL+"alpino?words="+urllib.parse.quote(t)) as r:
     38       q=r.read().decode("utf-8")
---> 39     i=q.index("conllu?tmp/")
```

@joostgrunwald it seems that [Alpino WebAPI](https://urd2.let.rug.nl/~vannoord/bin/alpino) went slow-down.

```
      6 nlp=spacy_alpino.load("Alpino/bin/Alpino")
```
This line seems from Google Colaboratory version. So I guess that https://www.let.rug.nl/vannoord/alp/Alpino/versions/binary/latest.tar.gz also went slow-down at that time.

>now doesn't work anymore on two different computers, a server and google collab

Well, in the server, have you already installed `Alpino` (and `xqilla`) as shown in [Installation with Alpino](https://github.com/KoichiYasuoka/spaCy-Alpino#installation-for-linux-debian-ubuntu-kali-with-alpino)?

**Comment by KoichiYasuoka** [comment]
I've just released `spaCy-Alpino` 0.7.6 with tentative patch for `Alpino` 2022-09-19. But I couldn't avoid WebAPI slow-down this time...

**Comment by joostgrunwald** [comment]
Found some interesting behaviour where it fails when double spaces are present:
"De  weerstand van veel kiezers tegen hem is te groot om zomaar te kunnen negeren." gives an error
while
"De weerstand van veel kiezers tegen hem is te groot om zomaar te kunnen negeren." works fine

**Comment by joostgrunwald** [comment]
some more issues concerning punctuation and sentence parsing are coming up 

>>> nlp("Na de uitslag van 15 mei zel de partij, mede de emoties in het land aftastend, een beslissing moeten nemen over het leiderschap van de PvdA.")
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    nlp("Na de uitslag van 15 mei zel de partij, mede de emoties in het land aftastend, een beslissing moeten nemen over het leiderschap van de PvdA.")
  File "C:\Users\joost\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py", line 1025, in __call__
    error_handler(name, proc, [doc], e)
  File "C:\Users\joost\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\util.py", line 1658, in raise_error
    raise e
  File "C:\Users\joost\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py", line 1020, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "C:\Users\joost\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy_alpino\alpino.py", line 71, in __call__
    doc.from_array([LEMMA,POS,TAG,DEP,HEAD],a)
  File "spacy\tokens\doc.pyx", line 1065, in spacy.tokens.doc.Doc.from_array
ValueError: [E971] Found incompatible lengths in `Doc.from_array`: 29 for the array and 28 for the Doc itself.
>>> nlp("Na de uitslag van 15 mei zel de partij, mede de emoties in het land aftastend, een beslissing moeten nemen over het leiderschap van de PvdA")
Na de uitslag van 15 mei zel de partij, mede de emoties in het land aftastend, een beslissing moeten nemen over het leiderschap van de PvdA
>>> 

The only difference above being the "." at the end.
@KoichiYasuoka

**Comment by KoichiYasuoka** [comment]
Sorry @joostgrunwald but in my circumstance of Google Colaboratory it works well:

```
!sudo apt install xqilla libxss1
!test -f Alpino.tar.gz || curl -L https://www.let.rug.nl/vannoord/alp/Alpino/versions/binary/latest.tar.gz -o Alpino.tar.gz
!test -d Alpino || tar xzf Alpino.tar.gz
!pip install spacy_alpino
import spacy_alpino
nlp=spacy_alpino.load("Alpino/bin/Alpino")
doc=nlp("Na de uitslag van 15 mei zel de partij, mede de emoties in het land aftastend, een beslissing moeten nemen over het leiderschap van de PvdA.")
import deplacy
deplacy.render(doc)
deplacy.serve(doc,port=None)
```

Which version of `spacy` do you use?

**Comment by KoichiYasuoka** [comment]
Thank you @joostgrunwald for the information, and now I suspect it is a bug of the tokenizer of Alpino itself. I've just tried Alpino directly in Google Colaboratory:

```
!test -f Alpino.tar.gz || curl -L https://www.let.rug.nl/vannoord/alp/Alpino/versions/binary/latest.tar.gz -o Alpino.tar.gz
!test -d Alpino || tar xzf Alpino.tar.gz
!rm -f [1-9]*.xml [1-9]*.tab*
!echo De weerstand van veel kiezers tegen hem is te groot om zomaar te kunnen negeren. | Alpino/Tokenization/tokenize.sh | Alpino/bin/Alpino -flag treebank . end_hook=xml -parse
!python2 Alpino/alpino2conll/tools/alpino2tab.py -c -f -p -r -t'\n' -w *.xml
!export ALPINO_HOME=Alpino ALPINO2CONLL_HOME=Alpino/alpino2conll ; for F in `ls -v *.tab` ; do python2 Alpino/alpino2conll/tools/tag.py -w2 -f $F ; cat $F'2' ; done
```

and I've got very questionable output from the latest version of Alpino:

```
/content/Alpino
hdrug: process 2267 on host 8f27f71c3e34 (datime(2022,10,20,12,0,55))
[De weerstand van veel kiezers tegen hem is te groot om zomaar te kunnen negeren .]
Q#1|De weerstand van veel kiezers tegen hem is te groot om zomaar te kunnen negeren .|1|1|-5.7942763877
converting 1.xml to 1.tab
retagging 1.tab to 1.tab2
['1', 'De', 'de', 'det', '2', 'det', '_', '_\n']
['2', 'weerstand', 'weerstand', 'noun', '8', 'su', '_', '_\n']
['3', 'van', 'van', 'prep', '2', 'mod', '_', '_\n']
['4', 'veel', 'veel', 'adj', '5', 'det', '_', '_\n']
['5', 'kiezers', 'kiezer', 'noun', '3', 'obj1', '_', '_\n']
['6', 'tegen', 'tegen', 'prep', '2', 'mod', '_', '_\n']
['7', 'hem', 'hem', 'pron', '6', 'obj1', '_', '_\n']
['8', 'is', 'ben', 'verb', '0', 'ROOT', '_', '_\n']
['9', 'te', 'te', 'adv', '10', 'mod', '_', '_\n']
['10', 'groot', 'groot', 'adj', '8', 'predc', '_', '_\n']
['11', 'om', 'om', 'comp', '9', 'obcomp', '_', '_\n']
['12', 'zomaar', 'zomaar', 'adv', '15', 'mod', '_', '_\n']
['13', 'te', 'te', 'comp', '11', 'body', '_', '_\n']
['14', 'kunnen', 'kan', 'verb', '13', 'body', '_', '_\n']
['15', 'negeren', 'negeer', 'verb', '14', 'vc', '_', '_\n']
['16', '.', '.', 'punct', '15', 'punct', '_', '_\n']
['\n']
Parse string with Alpino
['[ @mwu De ]', '[ @mwu weerstand ]', '[ @mwu van ]', '[ @mwu veel ]', '[ @mwu kiezers ]', '[ @mwu tegen ]', '[ @mwu hem ]', '[ @mwu is ]', '[ @mwu te ]', '[ @mwu groot ]', '[ @mwu om ]', '[ @mwu zomaar ]', '[ @mwu te ]', '[ @mwu kunnen ]', '[ @mwu negeren ]', '[ @mwu . ]']
hdrug: process 2303 on host 8f27f71c3e34 (datime(2022,10,20,12,1,2))
[De weerstand van veel kiezers tegen hem is te groot om zomaar te kunnen negeren .]
Q#1|[ @mwu De ] [ @mwu weerstand ] [ @mwu van ] [ @mwu veel ] [ @mwu kiezers ] [ @mwu tegen ] [ @mwu hem ] [ @mwu is ] [ @mwu te ] [ @mwu groot ] [ @mwu om ] [ @mwu zomaar ] [ @mwu te ] [ @mwu kunnen ] [ @mwu negeren ] [ @mwu . ]|1|1|-5.7942763877
OUT:
/content/Alpino
none/[0,0]|none|-- / --|./[15,16]|punct(punt)|1
none/[0,0]|none|-- / --|ben/[7,8]|[stype=declarative]:verb(unacc,sg_is,copula)|1
te/[8,9]|[]:vp_om_intensifier|hd/obcomp|om/[10,11]|[]:complementizer(om)|1
groot/[9,10]|[]:adjective(no_e(adv))|hd/mod|te/[8,9]|[]:vp_om_intensifier|1
om/[10,11]|[]:complementizer(om)|cmp/body|te/[12,13]|[]:complementizer(te)|1
te/[12,13]|[]:complementizer(te)|cmp/body|kan/[13,14]|[]:verb(hebben/zijn,inf,aux(inf))|1
tegen/[5,6]|[]:preposition(tegen,[aan,in,op])|hd/obj1|hem/[6,7]|[rnum=sg]:pronoun(nwh,thi,sg,de,dat_acc,def)|1
van/[2,3]|[]:preposition(van,[af,uit,vandaan,[af,aan]])|hd/obj1|kiezer/[4,5]|[rnum=pl,rnum=pl]:noun(de,count,pl)|1
negeer/[14,15]|[]:verb(hebben,inf,transitive)|hd/mod|zomaar/[11,12]|[]:adverb|1
kan/[13,14]|[]:verb(hebben/zijn,inf,aux(inf))|hd/vc|negeer/[14,15]|[]:verb(hebben,inf,transitive)|1
kiezer/[4,5]|[rnum=pl,rnum=pl]:noun(de,count,pl)|hd/det|veel/[3,4]|[]:adjective(no_e(odet_adv))|1
weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|hd/det|de/[0,1]|[]:determiner(de)|1
weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|hd/mod|tegen/[5,6]|[]:preposition(tegen,[aan,in,op])|1
weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|hd/mod|van/[2,3]|[]:preposition(van,[af,uit,vandaan,[af,aan]])|1
ben/[7,8]|[stype=declarative]:verb(unacc,sg_is,copula)|hd/predc|groot/[9,10]|[]:adjective(no_e(adv))|1
ben/[7,8]|[stype=declarative]:verb(unacc,sg_is,copula)|hd/su|weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|1

** none/[0,0]|none|-- / --|./[15,16]|punct(punt)|1
** none/[0,0]|none|-- / --|ben/[7,8]|[stype=declarative]:verb(unacc,sg_is,copula)|1
** te/[8,9]|[]:vp_om_intensifier|hd/obcomp|om/[10,11]|[]:complementizer(om)|1
** groot/[9,10]|[]:adjective(no_e(adv))|hd/mod|te/[8,9]|[]:vp_om_intensifier|1
** om/[10,11]|[]:complementizer(om)|cmp/body|te/[12,13]|[]:complementizer(te)|1
** te/[12,13]|[]:complementizer(te)|cmp/body|kan/[13,14]|[]:verb(hebben/zijn,inf,aux(inf))|1
** tegen/[5,6]|[]:preposition(tegen,[aan,in,op])|hd/obj1|hem/[6,7]|[rnum=sg]:pronoun(nwh,thi,sg,de,dat_acc,def)|1
** van/[2,3]|[]:preposition(van,[af,uit,vandaan,[af,aan]])|hd/obj1|kiezer/[4,5]|[rnum=pl,rnum=pl]:noun(de,count,pl)|1
** negeer/[14,15]|[]:verb(hebben,inf,transitive)|hd/mod|zomaar/[11,12]|[]:adverb|1
** kan/[13,14]|[]:verb(hebben/zijn,inf,aux(inf))|hd/vc|negeer/[14,15]|[]:verb(hebben,inf,transitive)|1
** kiezer/[4,5]|[rnum=pl,rnum=pl]:noun(de,count,pl)|hd/det|veel/[3,4]|[]:adjective(no_e(odet_adv))|1
** weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|hd/det|de/[0,1]|[]:determiner(de)|1
** weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|hd/mod|tegen/[5,6]|[]:preposition(tegen,[aan,in,op])|1
** weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|hd/mod|van/[2,3]|[]:preposition(van,[af,uit,vandaan,[af,aan]])|1
** ben/[7,8]|[stype=declarative]:verb(unacc,sg_is,copula)|hd/predc|groot/[9,10]|[]:adjective(no_e(adv))|1
** ben/[7,8]|[stype=declarative]:verb(unacc,sg_is,copula)|hd/su|weerstand/[1,2]|[rnum=sg]:noun(de,count,sg)|1
['de@[]:determiner(de)', 'none@none', 'weerstand@[rnum=sg]:noun(de,count,sg)', 'van@[]:preposition(van,[af,uit,vandaan,[af,aan]])', 'veel@[]:adjective(no_e(odet_adv))', 'kiezer@[rnum=pl,rnum=pl]:noun(de,count,pl)', 'tegen@[]:preposition(tegen,[aan,in,op])', 'hem@[rnum=sg]:pronoun(nwh,thi,sg,de,dat_acc,def)', 'ben@[stype=declarative]:verb(unacc,sg_is,copula)', 'te@[]:vp_om_intensifier', 'groot@[]:adjective(no_e(adv))', 'om@[]:complementizer(om)', 'zomaar@[]:adverb', 'te@[]:complementizer(te)', 'kan@[]:verb(hebben/zijn,inf,aux(inf))', 'negeer@[]:verb(hebben,inf,transitive)', '.@punct(punt)']
1	de	[]:determiner	de
2	none	non	none
3	weerstand	[rnum=sg]:noun	de|count|sg
4	van	[]:preposition	van|[af_uit_vandaan_[af_aan]]
5	veel	[]:adjective	no_e(odet_adv)
6	kiezer	[rnum=pl,rnum=pl]:noun	de|count|pl
7	tegen	[]:preposition	tegen|[aan_in_op]
8	hem	[rnum=sg]:pronoun	nwh|thi|sg|de|dat_acc|def
9	ben	[stype=declarative]:verb	unacc|sg_is|copula
10	te	[]:vp_om_intensifie	[]:vp_om_intensifier
11	groot	[]:adjective	no_e(adv)
12	om	[]:complementizer	om
13	zomaar	[]:adver	[]:adverb
14	te	[]:complementizer	te
15	kan	[]:verb	hebben/zijn|inf|aux(inf)
16	negeer	[]:verb	hebben|inf|transitive
17	.	punct	punt

tags:
1	de	[]:determiner	de
2	none	non	none
3	weerstand	[rnum=sg]:noun	de|count|sg
4	van	[]:preposition	van|[af_uit_vandaan_[af_aan]]
5	veel	[]:adjective	no_e(odet_adv)
6	kiezer	[rnum=pl,rnum=pl]:noun	de|count|pl
7	tegen	[]:preposition	tegen|[aan_in_op]
8	hem	[rnum=sg]:pronoun	nwh|thi|sg|de|dat_acc|def
9	ben	[stype=declarative]:verb	unacc|sg_is|copula
10	te	[]:vp_om_intensifie	[]:vp_om_intensifier
11	groot	[]:adjective	no_e(adv)
12	om	[]:complementizer	om
13	zomaar	[]:adver	[]:adverb
14	te	[]:complementizer	te
15	kan	[]:verb	hebben/zijn|inf|aux(inf)
16	negeer	[]:verb	hebben|inf|transitive
17	.	punct	punt

[['1', 'De', 'de', 'det', '2', 'det', '_', '_\n'], ['2', 'weerstand', 'weerstand', 'noun', '8', 'su', '_', '_\n'], ['3', 'van', 'van', 'prep', '2', 'mod', '_', '_\n'], ['4', 'veel', 'veel', 'adj', '5', 'det', '_', '_\n'], ['5', 'kiezers', 'kiezer', 'noun', '3', 'obj1', '_', '_\n'], ['6', 'tegen', 'tegen', 'prep', '2', 'mod', '_', '_\n'], ['7', 'hem', 'hem', 'pron', '6', 'obj1', '_', '_\n'], ['8', 'is', 'ben', 'verb', '0', 'ROOT', '_', '_\n'], ['9', 'te', 'te', 'adv', '10', 'mod', '_', '_\n'], ['10', 'groot', 'groot', 'adj', '8', 'predc', '_', '_\n'], ['11', 'om', 'om', 'comp', '9', 'obcomp', '_', '_\n'], ['12', 'zomaar', 'zomaar', 'adv', '15', 'mod', '_', '_\n'], ['13', 'te', 'te', 'comp', '11', 'body', '_', '_\n'], ['14', 'kunnen', 'kan', 'verb', '13', 'body', '_', '_\n'], ['15', 'negeren', 'negeer', 'verb', '14', 'vc', '_', '_\n'], ['16', '.', '.', 'punct', '15', 'punct', '_', '_\n'], ['\n']]
[['1', 'de', '[]:determiner', 'de'], ['2', 'none', 'non', 'none'], ['3', 'weerstand', '[rnum=sg]:noun', 'de|count|sg'], ['4', 'van', '[]:preposition', 'van|[af_uit_vandaan_[af_aan]]'], ['5', 'veel', '[]:adjective', 'no_e(odet_adv)'], ['6', 'kiezer', '[rnum=pl,rnum=pl]:noun', 'de|count|pl'], ['7', 'tegen', '[]:preposition', 'tegen|[aan_in_op]'], ['8', 'hem', '[rnum=sg]:pronoun', 'nwh|thi|sg|de|dat_acc|def'], ['9', 'ben', '[stype=declarative]:verb', 'unacc|sg_is|copula'], ['10', 'te', '[]:vp_om_intensifie', '[]:vp_om_intensifier'], ['11', 'groot', '[]:adjective', 'no_e(adv)'], ['12', 'om', '[]:complementizer', 'om'], ['13', 'zomaar', '[]:adver', '[]:adverb'], ['14', 'te', '[]:complementizer', 'te'], ['15', 'kan', '[]:verb', 'hebben/zijn|inf|aux(inf)'], ['16', 'negeer', '[]:verb', 'hebben|inf|transitive'], ['17', '.', 'punct', 'punt'], ['']]
18
LENGTH MISMATCH: split/join
de   De  llabe= det
t=  0
none   weerstand  llabe= noun
t=  1
weerstand   van  llabe= prep
t=  2
van   veel  llabe= adj
t=  3
veel   kiezers  llabe= noun
t=  4
kiezer   tegen  llabe= prep
t=  5
tegen   hem  llabe= pron
t=  6
hem   is  llabe= verb
t=  7
ben   te  llabe= adv
t=  8
te   groot  llabe= adj
t=  9
groot   om  llabe= comp
t=  10
om   zomaar  llabe= adv
t=  11
zomaar   te  llabe= comp
t=  12
te   kunnen  llabe= verb
t=  13
kan   negeren  llabe= verb
t=  14
negeer   .  llabe= punct
t=  15
***** PROBLEM WITH FILE  1.tab2
cat: 1.tab2: No such file or directory
```

In the result I found `none@none` was disasteous to destroy spaCy-Alpino. But Alpino itself is maintained by vannoord (Gertjan van Noord)...
